# Generated by Django 4.0.4 on 2022-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=10)),
                ('Adrs', models.TextField()),
                ('Mobnum', models.IntegerField()),
                ('Pin', models.IntegerField()),
            ],
        ),
    ]
