# Generated by Django 4.0.4 on 2022-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regtable',
            name='Password',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regtable',
            name='Username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
